project_id = "nmqycanqumelmfpdmkpr"

[functions.auth-callback]
verify_jwt = false

[functions.fetch-employees]
verify_jwt = false

[functions.add-technicians]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.manage-role]
verify_jwt = false
